//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libros
    {
        [Display (Name = "#")]
        public int idLibro { get; set; }
        [Display(Name = "Nombre del Libro")]
        public string nombreLibro { get; set; }
        [Display(Name = "Autor del Libro")]
        public string autorLibro { get; set; }
        [Display(Name = "Fecha de Lanzamiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime fechaLibro { get; set; }
    }
}
